@baseUrl=http://localhost:4001

// "https://to-do-ntrh.onrender.com"

# @baseUrl=https://to-do-ntrh.onrender.com

@token= eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NDgyY2UzNjRmNDViNTFhNWEyMWU4MzkiLCJpYXQiOjE2ODYyOTQyMDksImV4cCI6MTY4NjM4MDYwOX0.m6yXlKQ0fREixABpgkQgiUXhKioIWGKhStkZ7MiV8O4

###
GET {{baseUrl}}/


// signup the user into the database 
###
POST {{baseUrl}}/user/signup
content-type: application/json

{
"name":"A",
"email":"A",
"password": "111111",
"phone":"919068095967",
"role":"admin"
}

// to verify your account using the 6 word otp you received 

// this will make the user active and able to work further 
###
POST {{baseUrl}}/user/verify
content-type: application/json

{
  "email": "Ankitkaushik80@gmail.com",
  "otp":"226938"
}

// to login the user 
###
POST {{baseUrl}}/user/login
content-type: application/json

{
    "email":"A",
    "password":"111111"
}



// to logout the user 
###
POST {{baseUrl}}/user/logout
content-type: application/json
Authorization:Bearer {{token}}



// disable or delete user  ---- Soft delete functanility
###
DELETE  {{baseUrl}}/user/disable
content-type: application/json
Authorization:Bearer {{token}}


//  editing the all detail of the user 
###
PUT {{baseUrl}}/user/edit
content-type: application/json
Authorization:Bearer {{token}}

{
"name":"Ankit kaushik ",
"email":"an@gmail.com",
"password": "111111",
"phone":"912222222222",
"role":"user"
}

// delete the user permanently from db 
###
DELETE {{baseUrl}}/user/account
content-type: application/json
Authorization:Bearer {{token}}

// the task creation 
###

POST {{baseUrl}}/task/create
content-type: application/json
Authorization:Bearer {{token}}

{
"title":"the an",
"description":"the demo description ",
"priority": "easy",
"due_date":"2023-06-10T00:00:00.000Z"
}


// this endpoint will return all the task creatd by the logged in user (specific user)
###

GET {{baseUrl}}/task
content-type: application/json
Authorization:Bearer {{token}}

// to delete the task only creator can delete their task
###
DELETE  {{baseUrl}}/task/647f6d10be3127e244691816
content-type: application/json
Authorization:Bearer {{token}}

// get all the task only admin can get 
###
GET {{baseUrl}}/task/administration
content-type: application/json
Authorization:Bearer {{token}}

// to edit/ modify task by task id 
//only creator can modify their task
###
PUT {{baseUrl}}/task/edit/6481941617c58f42f1291c7e
content-type: application/json
Authorization:Bearer {{token}}

{
"title":"the update  ",
"description":"the new description ",
"priority": "easy",
"due_date":"2023-06-10T00:00:00.000Z"
}

// to assign the task to a user 
// enter the email for whom you want to assign task
// only the authorized person can assign the task --- who created the task and assignne are Authorized
###
POST {{baseUrl}}/task/assign/6482ced14f45b51a5a21e843
content-type: application/json
Authorization:Bearer {{token}}

{
  "assigneeEmail":"Ankitkaushik11@gmail.com"
}

// to change the status of the task 
// only assignne for whom task is assigned can be able to change the status of the task
###
POST {{baseUrl}}/task/status/6480169710b42a938115f6a4
content-type: application/json
Authorization:Bearer {{token}}

{
  "status":"inprogress"
}
