###
GET http://localhost:4001/


// signup the user into the database 
###
POST http://localhost:4001/api/auth/signup
content-type: application/json

{
"name":"Ankit123",
"email":"Ankit123@gmail.com",
"password": "111111",
"phone":"918930485009",
"role":"admin"
}


// to login the user into the database 
###
POST http://localhost:4001/api/auth/login
content-type: application/json

{
    "email":"Ankit12@gmail.com",
    "password":"111111"
}



// to logout the user into the database 
###
POST http://localhost:4001/api/auth/logout
content-type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NDdkODczOTc2MGQ2YTk3Nzk1MTg3NGQiLCJuYW1lIjoiQW5raXQiLCJlbWFpbCI6IkFua2l0MUBnbWFpbC5jb20iLCJpYXQiOjE2ODU5NTAxNTEsImV4cCI6MTY4NjAzNjU1MX0.du9PCyh3l3MIPE0LkrQXkTgfw8L5coPNXRcXoN_rJr0




// to verify your account using the 6 word otp you received 
// this will make the user active and able to work further 
###
POST http://localhost:4001/api/auth/verify
content-type: application/json

{
  "email": "Ankit12@gmail.com",
  "otp":"930938"
}


// the task creation 
// in assignne we entered the id's of the users who can see this task or for whom the task is created 
###

POST http://localhost:4001/api/task/create
content-type: application/json

{
"userId":"647d8739760d6a977951874d",
"title":"want to fo for a walkk ",
"description":"walking is good for health",
"priority": "easy",
"due_date":"2023-06-10T00:00:00.000Z",
"assignee":["abc","def"],
"status":"done"
}


// to get all the task specified made by particular person 
###

POST http://localhost:4001/api/task/get
content-type: application/json

{
  "created_by":"647d8739760d6a977951874d"
}

###
DELETE  http://localhost:4001/api/task/delete/647da8e08b3664c863c81cbd
content-type: application/json

{
  "created_by":"647d8739760d6a977951874d"
}


###
POST http://localhost:4001/api/task/administration/647dd86ae68ae20e29f3b110
content-type: application/json
